name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vite-react-app .

      # Push Docker image to Docker Hub (optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag vite-react-app chiqors/frontend:v3
          docker push chiqors/frontend:v3
